


- name: "Git: is it up-to-date?"
  git:
    repo: git@github.com:media-byte/saltbox_mod.git
    dest: /opt/saltbox_mod
    update: yes
    version: master
  register: git
  ignore_errors: True
- debug:
    var: git

- name: Git - Adding
  shell: "git add *"
  args:
    chdir: /opt/saltbox_mod
  register: gitadd
  when: git.msg is defined
- debug:
    var: gitadd.cmd

- name: Git - commiting
  shell: git commit -m "Updating saltbox mod repo" 
  args:
    chdir: /opt/saltbox_mod
  register: gitcommit
  when: git.msg is defined
- debug:
    var: gitcommit.stdout

- name: Git - push
  shell: git push 
  args:
    chdir: /opt/saltbox_mod
  register: gitpush
  when: git.msg is defined
- debug:
    var: gitpush