#########################################################################
# Title:            Sandbox Mod: Audiobook-Automation                   #
# Author(s):        hackmonker                                          #
# URL:              https://github.com/media-byte/saltbox_mod           #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

m4btool_name: m4btool

################################
# Paths
################################

m4btool_paths_folder: "{{ m4btool_name }}"
m4btool_paths_location: "{{ server_appdata_path }}/ab-automation/{{ m4btool_paths_folder }}"
m4btool_paths_folders_list:
  - "{{ m4btool_paths_location }}"

################################
# Docker
################################

# Container
m4btool_docker_container: "{{ m4btool_name }}"

# Image
m4btool_docker_image_pull: true
m4btool_docker_image_tag: "latest"
m4btool_docker_image: "ghcr.io/media-byte/auto-m4btool:{{ m4btool_docker_image_tag }}"

# Envs
m4btool_docker_envs_default:
  TZ: "{{ tz }}"
m4btool_docker_envs_custom: {}
m4btool_docker_envs: "{{ m4btool_docker_envs_default
                         | combine(m4btool_docker_envs_custom) }}"

# Commands
m4btool_docker_commands_default: []
m4btool_docker_commands_custom: []
m4btool_docker_commands: "{{ m4btool_docker_commands_default
                             + m4btool_docker_commands_custom }}"

# Volumes
m4btool_docker_volumes_default:
  - "{{ m4btool_paths_location }}:/config"
m4btool_docker_volumes_custom:
  - "/mnt/local/downloads/audiobooks/temp:/temp"
m4btool_docker_volumes: "{{ m4btool_docker_volumes_default
                            + m4btool_docker_volumes_custom }}"

# Devices
m4btool_docker_devices_default: []
m4btool_docker_devices_custom: []
m4btool_docker_devices: "{{ m4btool_docker_devices_default
                            + m4btool_docker_devices_custom }}"

# Hosts
m4btool_docker_hosts_default: []
m4btool_docker_hosts_custom: []
m4btool_docker_hosts: "{{ docker_hosts_common
                          | combine(m4btool_docker_hosts_default)
                          | combine(m4btool_docker_hosts_custom) }}"

# Labels
m4btool_docker_labels_default: {}
m4btool_docker_labels_custom: {}
m4btool_docker_labels: "{{ docker_labels_common
                           | combine(m4btool_docker_labels_default)
                           | combine(m4btool_docker_labels_custom) }}"

# Hostname
m4btool_docker_hostname: "{{ m4btool_name }}"

# Networks
m4btool_docker_networks_alias: "{{ m4btool_name }}"
m4btool_docker_networks_default: []
m4btool_docker_networks_custom: []
m4btool_docker_networks: "{{ docker_networks_common
                             + m4btool_docker_networks_default
                             + m4btool_docker_networks_custom }}"

# Capabilities
m4btool_docker_capabilities_default: []
m4btool_docker_capabilities_custom: []
m4btool_docker_capabilities: "{{ m4btool_docker_capabilities_default
                                 + m4btool_docker_capabilities_custom }}"

# Security Opts
m4btool_docker_security_opts_default: []
m4btool_docker_security_opts_custom: []
m4btool_docker_security_opts: "{{ m4btool_docker_security_opts_default
                                  + m4btool_docker_security_opts_custom }}"

# Restart Policy
m4btool_docker_restart_policy: unless-stopped

# State
m4btool_docker_state: started

# Stop Timeout
m4btool_docker_stop_timeout: 10

# User
m4btool_docker_user: "{{ uid }}:{{ gid }}"