#########################################################################
# Title:            Sandbox Mod: Plextraktsync                          #
# Author(s):        hackmonker                                          #
# URL:              https://github.com/media-byte/saltbox_mod           #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Plextraktsync tasks"
  include_tasks: main2.yml
  vars:
    plextraktsync_name: "plextraktsync-{{ plexuser }}"
    plextraktsync_paths_location: "{{ server_appdata_path }}/plextraktsync/{{ plexuser }}"
  with_items: "{{ plextraktsync.plexusers }}"
  loop_control:
    loop_var: plexuser