#########################################################################
# Title:            Sandbox Mod: Plextraktsync                          #
# Author(s):        hackmonker                                          #
# URL:              https://github.com/media-byte/saltbox_mod           #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Check if `{{ plextraktsync_paths_config_location | basename }}` exists
  stat:
    path: "{{ plextraktsync_paths_config_location }}"
  register: plextraktsync_env

- name: Pre-Install Tasks
  include_tasks: "subtasks/pre-install/main.yml"
  when: not plextraktsync_env.stat.exists

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Runs the plextraktsync command every 12 hours
  ansible.builtin.cron:
    name: "Run plextraktsync sync"
    minute: "0"
    hour: "*/12"
    job: "/bin/bash /opt/plextraktsync/pts.sh && curl -fsS --retry 5 -o /dev/null https://hc-ping.com/145f3b49-fab2-4bb6-980d-95457f095ed9"
    user: "{{ user.name }}"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
