#########################################################################
# Title:            Sandbox Mod: Audiobook-Automation                   #
# Author(s):        hackmonker                                          #
# URL:              https://github.com/media-byte/saltbox_mod           #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: yes
  with_items:
  - "{{ m4btool_paths_location }}"
  - "/mnt/local/downloads/audiobooks/temp/untagged"
  - "/mnt/local/downloads/audiobooks/temp/mp3merge"
  - "/mnt/local/downloads/audiobooks/temp/delete"

- name: Install Organize-Tool
  pip:
    name: organize-tool
  ignore_errors: yes

- name: Runs the organizr command every 5 mins
  cron:
    name: "Move Audiobook files"
    minute: "5"
    job: "/usr/local/bin/organize run /opt/ab-automation/organize/config.yaml"
    user: "{{ user.name }}"

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
